/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 bunny.gltf --transform 
Files: bunny.gltf [6.21MB] > bunny-transformed.glb [246.02KB] (96%)
Author: NishaMartel (https://sketchfab.com/NishaMartel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-rabbit-ed8b2d79eaa44bdeb70ae72c162539b2
Title: Cute rabbit
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bunny-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.lambert1}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload('/bunny-transformed.glb');
