/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 yin.gltf --transform 
Files: yin.gltf [327.7KB] > yin-transformed.glb [123.45KB] (62%)
Author: madexc (https://sketchfab.com/madexc)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/yin-yang-06446db8e9f54d299ddd967d04c14a72
Title: yin-yang
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('./yin-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Wool}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('./yin-transformed.glb');
